### ISSUE TITLE
console service proxy only works with port 2080

### ISSUE THREAD

**Issue by acobster** [sitecrafting/lando-beanstalkd#2]
Configuring a proxy for a `beanstalkd_console` service only works at port 2080:

```
name: lamp
recipe: lamp
config:
  webroot: www
services:
  queue:
    type: beanstalkd
    portforward: 11333
  console:
    type: beanstalkd_console
    beanstalkd_host: queue
proxy:
  console:
    - beanstalk.lamp.lndo.site
```

On my setup (Ubuntu 16.04, Lando beta.35), running `lando start` with this proxy config results in a proxy at http://beanstalk.lamp.lndo.site:8000.

Specifying any other port (or no port) results in a "bad" proxy, i.e. a Bad Gateway error.
